# Schema for the configuration file of image migration module.

images_migration.settings:
  type: config_object
  label: 'Images Migration Settings'
  mapping:
    source_path:
      type: sequence
      label: 'Source Path that contains original images'
      sequence:
        type: string
        label: 'Source Path'
    destination_path:
      type: sequence
      label: 'Destination Path that contains copied images'
      sequence:
        type: string
        label: 'Destination Path'
    content_type_list:
      type: sequence
      label: 'List of Content Types'
      sequence:
        type: string
        label: 'Content Type List'
    db_name:
      type: sequence
      label: 'Database name of the source site'
      sequence:
        type: string
        label: 'Database Name'